class SQLValidator:
    """
    Validates SQL generated by the LLM before execution.
    """

    FORBIDDEN_KEYWORDS = [
        "DROP",
        "DELETE",
        "UPDATE",
        "INSERT",
        "ALTER",
        "TRUNCATE",
        "CREATE"
    ]

    def validate(self, response):
        """
        Validate and clean the LLM response.
        """
        response = self.remove_markdown(response)

        self.check_schema_not_found(response)

        self.check_forbidden_keywords(response)

        response = self.extract_sql(response)

        self.check_select_statement(response)

        return response
    
    def remove_markdown(self, text):
        """
        Remove markdown code fences.
        """

        text = text.replace("```sql", "")
        text = text.replace("```", "")

        return text.strip()
    
    def extract_sql(self, text):
        """
        Extract only the SQL query from the LLM response.
        """

        lines = text.splitlines()

        sql_lines = []

        found_sql = False

        for line in lines:

            stripped = line.strip()

            if not stripped:
                continue

            upper = stripped.upper()

            if (
                upper.startswith("SELECT")
                or upper.startswith("WITH")
            ):
                found_sql = True

            if found_sql:
                sql_lines.append(stripped)

        return "\n".join(sql_lines).strip()
    
    def check_schema_not_found(self, text):
        """
        Check whether the model could not answer using the schema.
        """

        if "SCHEMA_NOT_FOUND" in text.upper():

            raise ValueError(
                "Requested information is not available in the database schema."
            )
        
    def check_forbidden_keywords(self, sql):
        """
        Reject dangerous SQL statements.
        """

        sql_upper = sql.upper()

        for keyword in self.FORBIDDEN_KEYWORDS:

            if keyword in sql_upper:

                raise ValueError(
                    f"Forbidden SQL statement detected: {keyword}"
                )
            
    def check_select_statement(self, sql):
        """
        Ensure that only SELECT queries are executed.
        """

        sql = sql.strip().upper()

        if not (
            sql.startswith("SELECT")
            or sql.startswith("WITH")
        ):

            raise ValueError(
                "Only SELECT queries are allowed."
            )
        
    